-- ============================================================
-- MISSING TABLES MIGRATION — Admin Panel Full Supabase Sync
-- Run this in your Supabase SQL Editor
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- 1. MESSAGE TEMPLATES
-- Stores WhatsApp / SMS / Email communication templates
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.message_templates (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name         TEXT NOT NULL,
    category     TEXT NOT NULL DEFAULT 'whatsapp' CHECK (category IN ('whatsapp', 'sms', 'email')),
    subject      TEXT,                              -- for email only
    body         TEXT NOT NULL,
    variables    TEXT[] DEFAULT '{}',              -- e.g. {customer_name}, {car_model}
    is_active    BOOLEAN DEFAULT true,
    usage_count  INT DEFAULT 0,
    created_by   UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at   TIMESTAMPTZ DEFAULT now(),
    updated_at   TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.message_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins manage message_templates" ON public.message_templates;
CREATE POLICY "Admins manage message_templates"
    ON public.message_templates FOR ALL
    USING (public.is_admin());
DROP POLICY IF EXISTS "Staff read message_templates" ON public.message_templates;
CREATE POLICY "Staff read message_templates"
    ON public.message_templates FOR SELECT
    TO authenticated USING (true);

-- ─────────────────────────────────────────────────────────────
-- 2. MANUAL TRANSACTIONS
-- Allows admins to log custom income/expense entries (petty cash, rent, misc)
-- These appear in the Accounts ledger alongside auto-derived entries
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.manual_transactions (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    description  TEXT NOT NULL,
    type         TEXT NOT NULL CHECK (type IN ('income', 'expense')),
    amount       NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    mode         TEXT DEFAULT 'Cash' CHECK (mode IN ('Cash', 'Bank Transfer', 'UPI', 'Cheque', 'Card', 'Other')),
    category     TEXT DEFAULT 'General',
    notes        TEXT,
    status       TEXT DEFAULT 'Completed' CHECK (status IN ('Completed', 'Pending')),
    transaction_date DATE DEFAULT CURRENT_DATE,
    created_by   UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at   TIMESTAMPTZ DEFAULT now(),
    updated_at   TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.manual_transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins manage manual_transactions" ON public.manual_transactions;
CREATE POLICY "Admins manage manual_transactions"
    ON public.manual_transactions FOR ALL
    USING (public.is_admin());

-- ─────────────────────────────────────────────────────────────
-- 3. TAX FILINGS
-- Stores GST filing records — when filed, by whom, for which month
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tax_filings (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    month_key       TEXT NOT NULL UNIQUE,          -- e.g. '2026-07' (YYYY-MM)
    month_label     TEXT NOT NULL,                 -- e.g. 'July 2026'
    cgst_amount     NUMERIC(12,2) DEFAULT 0,
    sgst_amount     NUMERIC(12,2) DEFAULT 0,
    net_payable     NUMERIC(12,2) DEFAULT 0,
    taxable_margin  NUMERIC(12,2) DEFAULT 0,
    status          TEXT DEFAULT 'due' CHECK (status IN ('due', 'filed', 'overdue')),
    filed_at        TIMESTAMPTZ,
    filed_by        UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    filed_by_name   TEXT,                          -- snapshot of name at filing time
    reference_no    TEXT,                          -- GST filing reference number
    notes           TEXT,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.tax_filings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins manage tax_filings" ON public.tax_filings;
CREATE POLICY "Admins manage tax_filings"
    ON public.tax_filings FOR ALL
    USING (public.is_admin());

-- ─────────────────────────────────────────────────────────────
-- 4. REPORT HISTORY
-- Persists metadata of every CSV export generated by the admin
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.report_history (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    report_type   TEXT NOT NULL,                   -- 'Sales Report', 'Inventory Report', etc.
    filters_json  JSONB DEFAULT '{}',              -- date_from, date_to, other filters
    row_count     INT DEFAULT 0,
    file_name     TEXT NOT NULL,
    file_size_kb  NUMERIC(8,2) DEFAULT 0,
    generated_by  UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    generated_by_name TEXT,                        -- snapshot of name
    created_at    TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.report_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins manage report_history" ON public.report_history;
CREATE POLICY "Admins manage report_history"
    ON public.report_history FOR ALL
    USING (public.is_admin());
DROP POLICY IF EXISTS "Staff view own report_history" ON public.report_history;
CREATE POLICY "Staff view own report_history"
    ON public.report_history FOR SELECT
    TO authenticated
    USING (generated_by = auth.uid());

-- ─────────────────────────────────────────────────────────────
-- 5. CUSTOMER ALERT CONFIGS (OPTIONAL — for future configurable thresholds)
-- Currently CustomerAlerts uses RPC get_expiring_documents which is already synced
-- This table stores user-configurable alert preferences
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.customer_alert_configs (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    alert_type    TEXT NOT NULL,                   -- 'expiring_docs', 'follow_up_overdue', etc.
    days_threshold INT DEFAULT 60,                 -- days ahead to alert
    is_enabled    BOOLEAN DEFAULT true,
    notify_email  BOOLEAN DEFAULT false,
    notify_push   BOOLEAN DEFAULT true,
    created_at    TIMESTAMPTZ DEFAULT now(),
    updated_at    TIMESTAMPTZ DEFAULT now(),
    UNIQUE(user_id, alert_type)
);

ALTER TABLE public.customer_alert_configs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users manage own alert_configs" ON public.customer_alert_configs;
CREATE POLICY "Users manage own alert_configs"
    ON public.customer_alert_configs FOR ALL
    USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Admins manage all alert_configs" ON public.customer_alert_configs;
CREATE POLICY "Admins manage all alert_configs"
    ON public.customer_alert_configs FOR ALL
    USING (public.is_admin());

-- ─────────────────────────────────────────────────────────────
-- 6. ENSURE FOLLOW_UPS TABLE EXISTS (V2 — if not already created)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.follow_ups (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    lead_id              UUID REFERENCES public.leads(id) ON DELETE CASCADE,
    type                 TEXT DEFAULT 'Call' CHECK (type IN ('Call', 'WhatsApp', 'Email', 'Visit', 'Task')),
    notes                TEXT,
    next_followup_date   TIMESTAMPTZ,
    is_done              BOOLEAN DEFAULT false,
    priority             TEXT DEFAULT 'Warm' CHECK (priority IN ('Hot', 'Warm', 'Cold')),
    created_by           UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at           TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.follow_ups ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins manage follow_ups" ON public.follow_ups;
CREATE POLICY "Admins manage follow_ups"
    ON public.follow_ups FOR ALL USING (public.is_admin());
DROP POLICY IF EXISTS "Staff manage own follow_ups" ON public.follow_ups;
CREATE POLICY "Staff manage own follow_ups"
    ON public.follow_ups FOR ALL TO authenticated
    USING (created_by = auth.uid() OR public.is_admin());

-- ─────────────────────────────────────────────────────────────
-- 7. ENSURE FINANCE_SERVICES TABLE EXISTS
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.finance_services (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type              TEXT NOT NULL DEFAULT 'loan' CHECK (type IN ('loan', 'insurance')),
    customer_id       UUID REFERENCES public.customers(id) ON DELETE SET NULL,
    car_id            UUID REFERENCES public.inventory(id) ON DELETE SET NULL,
    full_name         TEXT NOT NULL,
    phone             TEXT,
    email             TEXT,
    status            TEXT DEFAULT 'pending',
    provider_name     TEXT,
    amount            NUMERIC(12,2),
    tenure_months     INT,
    interest_rate     NUMERIC(5,2),
    premium_amount    NUMERIC(12,2),
    policy_number     TEXT,
    commission_earned NUMERIC(12,2) DEFAULT 0,
    notes             TEXT,
    expiry_date       DATE,
    created_by        UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at        TIMESTAMPTZ DEFAULT now(),
    updated_at        TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.finance_services ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins manage finance_services" ON public.finance_services;
CREATE POLICY "Admins manage finance_services"
    ON public.finance_services FOR ALL USING (public.is_admin());
DROP POLICY IF EXISTS "Staff manage finance_services" ON public.finance_services;
CREATE POLICY "Staff manage finance_services"
    ON public.finance_services FOR ALL TO authenticated
    USING (true);

-- ─────────────────────────────────────────────────────────────
-- 8. ENSURE INCENTIVES TABLE EXISTS
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.incentives (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    staff_id        UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    amount          NUMERIC(12,2) NOT NULL,
    reason          TEXT NOT NULL,
    incentive_type  TEXT NOT NULL DEFAULT 'bonus',
    month           TEXT NOT NULL,                 -- 'YYYY-MM'
    notes           TEXT,
    created_by      UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.incentives ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins manage incentives" ON public.incentives;
CREATE POLICY "Admins manage incentives"
    ON public.incentives FOR ALL USING (public.is_admin());
DROP POLICY IF EXISTS "Staff read own incentives" ON public.incentives;
CREATE POLICY "Staff read own incentives"
    ON public.incentives FOR SELECT TO authenticated
    USING (staff_id = auth.uid() OR public.is_admin());

-- ─────────────────────────────────────────────────────────────
-- 9. ENSURE ANNOUNCEMENTS TABLE EXISTS (for Incentives page)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.announcements (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title       TEXT NOT NULL,
    body        TEXT NOT NULL,
    priority    TEXT DEFAULT 'normal' CHECK (priority IN ('normal', 'urgent', 'celebration')),
    is_pinned   BOOLEAN DEFAULT false,
    expires_at  TIMESTAMPTZ,
    created_by  UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ DEFAULT now(),
    updated_at  TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins manage announcements" ON public.announcements;
CREATE POLICY "Admins manage announcements"
    ON public.announcements FOR ALL USING (public.is_admin());
DROP POLICY IF EXISTS "Staff read announcements" ON public.announcements;
CREATE POLICY "Staff read announcements"
    ON public.announcements FOR SELECT TO authenticated USING (true);

-- ─────────────────────────────────────────────────────────────
-- 10. ENSURE VISITS TABLE EXISTS (DataContext fetches from this)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.visits (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    staff_id      UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    lead_id       UUID REFERENCES public.leads(id) ON DELETE SET NULL,
    customer_id   UUID REFERENCES public.customers(id) ON DELETE SET NULL,
    visit_type    TEXT DEFAULT 'showroom' CHECK (visit_type IN ('showroom', 'field', 'call', 'online')),
    purpose       TEXT,
    outcome       TEXT,
    notes         TEXT,
    visit_date    TIMESTAMPTZ DEFAULT now(),
    created_at    TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.visits ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins manage visits" ON public.visits;
CREATE POLICY "Admins manage visits"
    ON public.visits FOR ALL USING (public.is_admin());
DROP POLICY IF EXISTS "Staff manage own visits" ON public.visits;
CREATE POLICY "Staff manage own visits"
    ON public.visits FOR ALL TO authenticated
    USING (staff_id = auth.uid() OR public.is_admin());

-- ─────────────────────────────────────────────────────────────
-- 11. ENSURE CLUB_SERVICE_EXCHANGES TABLE EXISTS
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.club_service_exchanges (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    member_id        UUID REFERENCES public.club_members(id) ON DELETE CASCADE,
    service_type     TEXT NOT NULL,
    points_used      INT DEFAULT 0,
    points_earned    INT DEFAULT 0,
    description      TEXT,
    transaction_date DATE DEFAULT CURRENT_DATE,
    added_by         UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at       TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.club_service_exchanges ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins manage club_service_exchanges" ON public.club_service_exchanges;
CREATE POLICY "Admins manage club_service_exchanges"
    ON public.club_service_exchanges FOR ALL USING (public.is_admin());

-- ─────────────────────────────────────────────────────────────
-- 12. ENSURE DEALER_SETTLEMENTS TABLE EXISTS (DealerManagement uses it)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.dealer_settlements (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    dealer_id        UUID REFERENCES public.dealers(id) ON DELETE CASCADE,
    inventory_id     UUID REFERENCES public.inventory(id) ON DELETE SET NULL,
    amount           NUMERIC(12,2) NOT NULL,
    settlement_date  DATE,
    status           TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'paid')),
    notes            TEXT,
    created_at       TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.dealer_settlements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins manage dealer_settlements" ON public.dealer_settlements;
CREATE POLICY "Admins manage dealer_settlements"
    ON public.dealer_settlements FOR ALL USING (public.is_admin());

-- ─────────────────────────────────────────────────────────────
-- 13. ADD MISSING COLUMNS TO EXISTING TABLES (safe ALTER)
-- ─────────────────────────────────────────────────────────────

-- profiles: add department and is_active if missing
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS department TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS avatar_url TEXT;

-- inventory: add thumbnail, dealer_id, dealer_asking_price, our_margin, dealer_commission
ALTER TABLE public.inventory ADD COLUMN IF NOT EXISTS thumbnail TEXT;
ALTER TABLE public.inventory ADD COLUMN IF NOT EXISTS license_plate TEXT;
ALTER TABLE public.inventory ADD COLUMN IF NOT EXISTS dealer_id UUID REFERENCES public.dealers(id) ON DELETE SET NULL;
ALTER TABLE public.inventory ADD COLUMN IF NOT EXISTS dealer_asking_price NUMERIC(12,2);
ALTER TABLE public.inventory ADD COLUMN IF NOT EXISTS our_margin NUMERIC(12,2);
ALTER TABLE public.inventory ADD COLUMN IF NOT EXISTS dealer_commission NUMERIC(12,2);

-- dealers: add missing columns referenced in DealerManagement
ALTER TABLE public.dealers ADD COLUMN IF NOT EXISTS dealer_code TEXT UNIQUE;
ALTER TABLE public.dealers ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.dealers ADD COLUMN IF NOT EXISTS alternate_phone TEXT;
ALTER TABLE public.dealers ADD COLUMN IF NOT EXISTS whatsapp_number TEXT;
ALTER TABLE public.dealers ADD COLUMN IF NOT EXISTS gst_number TEXT;
ALTER TABLE public.dealers ADD COLUMN IF NOT EXISTS notes TEXT;

-- sales: add car_id as alias for inventory_id (some pages use car_id)
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS car_id UUID REFERENCES public.inventory(id) ON DELETE SET NULL;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS final_price NUMERIC(12,2);
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS sale_price NUMERIC(12,2);
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS customer_id UUID REFERENCES public.customers(id) ON DELETE SET NULL;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS customer_name TEXT;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS customer_phone TEXT;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS customer_email TEXT;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS sale_type TEXT DEFAULT 'purchased';
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS sold_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'paid';
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS purchase_cost_snapshot NUMERIC(12,2);
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS profit NUMERIC(12,2);
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'completed';

-- customers: add missing columns
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS city TEXT;

-- leads: add full_name, assigned_to FK to profiles
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'buy';
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS expected_close_date DATE;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS assigned_to UUID;

-- tasks: add created_by for audit
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;

-- attendance_records: ensure staff_id uses profiles reference too
ALTER TABLE public.attendance_records ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;

-- ─────────────────────────────────────────────────────────────
-- 14. ENABLE REALTIME ON NEW TABLES
-- ─────────────────────────────────────────────────────────────
DO $$
BEGIN
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.message_templates;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.manual_transactions;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.tax_filings;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.report_history;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.follow_ups;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.incentives;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.announcements;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.visits;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.finance_services;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
END;
$$;

-- ============================================================
-- DONE. All missing tables created, columns added, RLS applied.
-- ============================================================
